import { describe, it, expect, vi } from 'vitest'
import { mount } from '@vue/test-utils'
import { computed } from 'vue'

import SingleValue from '../src/components/SingleValue.vue'
import type { TreeselectInstance, TreeselectNode } from '../src/types'
import { TRESELECT_INSTANCE_KEY } from '../src/types'

describe('Task 9: SingleValue Component', () => {
  it('should render selected node label', () => {
    const mockNode: TreeselectNode = {
      id: 'a',
      label: 'Option A',
      lowerLabel: 'option a',
      lowerCased: {},
      nestedSearchLabel: 'option a',
      isLeaf: true,
      isBranch: false,
      isDisabled: false,
      isNew: false,
      isMatched: false,
      isHighlighted: false,
      hasMatchedDescendants: false,
      hasDisabledDescendants: false,
      hasChildren: false,
      hasLoadedChildren: true,
      isExpanded: false,
      isExpandedOnSearch: false,
      showAllChildrenOnSearch: false,
      isLoading: false,
      loadingError: '',
      childrenStates: { isLoaded: true, isLoading: false, loadingError: '' },
      count: { ALL_CHILDREN: 0, ALL_DESCENDANTS: 0, LEAF_CHILDREN: 0, LEAF_DESCENDANTS: 0 },
      isSelected: true,
      level: 0,
      index: [0],
      ancestors: [],
      parentNode: null,
      isRootNode: true,
      isFallbackNode: false,
      children: [],
      raw: { id: 'a', label: 'Option A' },
    }

    const mockInstance: TreeselectInstance = {
      trigger: {
        isFocused: false,
        searchQuery: '',
      },
      menuIsOpen: false,
      currentHighlightedOptionId: null,
      selectedNodes: [mockNode],
      hasValue: true,
      single: true,
      multiple: false,
      hasBranchNodes: false,
      localSearch: {
        active: false,
        noResults: true,
        countMap: {},
      },
      forest: {
        normalizedOptions: [],
        nodeMap: {},
        checkedStateMap: {},
        selectedNodeIds: [],
        selectedNodeMap: {},
      },
      rootOptionsStates: {
        isLoaded: false,
        isLoading: false,
        loadingError: '',
      },
      showCount: false,
      showCountOf: 'ALL_CHILDREN',
      showCountOnSearchComputed: false,
      noChildrenText: 'No sub-options.',
      loadingText: 'Loading...',
      retryTitle: 'Click to retry',
      retryText: 'Retry?',
      shouldFlattenOptions: false,
      shouldExpand: vi.fn(),
      shouldShowOptionInMenu: vi.fn(() => true),
      setCurrentHighlightedOption: vi.fn(),
      removeLastValue: vi.fn(),
      disabled: false,
      searchable: true,
      placeholder: 'Select...',
      clearable: true,
      allowClearingDisabled: false,
      clearAllText: 'Clear all',
      clearValueText: 'Clear value',
      alwaysOpen: false,
      openOnFocus: false,
      autoFocus: false,
      tabIndex: 0,
      backspaceRemoves: true,
      deleteRemoves: true,
      limit: Infinity,
      limitText: vi.fn(),
      valueFormat: 'id',
      delimiter: ',',
      openMenu: vi.fn(),
      closeMenu: vi.fn(),
      clear: vi.fn(),
      focusInput: vi.fn(),
      blurInput: vi.fn(),
      getSelectedNodes: vi.fn(() => [mockNode]),
      getNode: vi.fn(() => mockNode),
      isSelected: vi.fn(() => true),
      toggleExpanded: vi.fn(),
      select: vi.fn(),
      loadChildrenOptions: vi.fn(),
      getInstanceId: vi.fn(() => 'test'),
      getValue: vi.fn(),
      initialize: vi.fn(),
      buildForestState: vi.fn(),
      shouldOptionBeIncludedInSearchResult: vi.fn(() => false),
      traverseAllNodesByIndex: vi.fn(),
      extractCheckedNodeIdsFromValue: vi.fn(() => []),
      fixSelectedNodeIds: vi.fn(),
      enhancedNormalizer: vi.fn((o) => o),
      toggleMenu: vi.fn(),
      resetHighlightedOptionWhenNecessary: vi.fn(),
      highlightFirstOption: vi.fn(),
      highlightPrevOption: vi.fn(),
      highlightNextOption: vi.fn(),
      highlightLastOption: vi.fn(),
      visibleOptionIds: [],
      setMenuGetter: vi.fn(),
      setControlGetter: vi.fn(),
      setInputGetter: vi.fn(),
      handleLocalSearch: vi.fn(),
      resetSearchQuery: vi.fn(),
      loadRootOptions: vi.fn(),
      callLoadOptionsProp: vi.fn(),
      handleMouseDown: vi.fn(),
      setup: vi.fn(),
      onMount: vi.fn(),
      onUnmount: vi.fn(),
      remoteSearch: {},
      noOptionsText: 'No options available.',
      noResultsText: 'No results found.',
      searchPromptText: 'Type to search...',
      getRemoteSearchEntry: vi.fn(() => ({ isLoaded: false, isLoading: false, loadingError: '', options: [] })),
      handleRemoteSearch: vi.fn(),
      openDirection: 'auto',
      getMenu: vi.fn(() => null),
      getControl: vi.fn(() => null),
      menu: {
        isOpen: false,
        current: null,
        lastScrollPosition: 0,
        placement: 'bottom',
      },
      getValueContainer: vi.fn(() => null),
      setValueContainerGetter: vi.fn(),
      setupHandleClickOutside: vi.fn(),
    }

    const wrapper = mount(SingleValue, {
      global: {
        provide: {
          [TRESELECT_INSTANCE_KEY as symbol]: computed(() => mockInstance),
        },
      },
    })

    expect(wrapper.find('.vue-treeselect__single-value').exists()).toBe(true)
    expect(wrapper.text()).toContain('Option A')
  })

  it('should not render when hasValue is false', () => {
    const mockInstance: TreeselectInstance = {
      trigger: {
        isFocused: false,
        searchQuery: '',
      },
      menuIsOpen: false,
      currentHighlightedOptionId: null,
      selectedNodes: [],
      hasValue: false,
      single: true,
      multiple: false,
      hasBranchNodes: false,
      localSearch: {
        active: false,
        noResults: true,
        countMap: {},
      },
      forest: {
        normalizedOptions: [],
        nodeMap: {},
        checkedStateMap: {},
        selectedNodeIds: [],
        selectedNodeMap: {},
      },
      rootOptionsStates: {
        isLoaded: false,
        isLoading: false,
        loadingError: '',
      },
      showCount: false,
      showCountOf: 'ALL_CHILDREN',
      showCountOnSearchComputed: false,
      noChildrenText: 'No sub-options.',
      loadingText: 'Loading...',
      retryTitle: 'Click to retry',
      retryText: 'Retry?',
      shouldFlattenOptions: false,
      shouldExpand: vi.fn(),
      shouldShowOptionInMenu: vi.fn(() => true),
      setCurrentHighlightedOption: vi.fn(),
      removeLastValue: vi.fn(),
      disabled: false,
      searchable: true,
      placeholder: 'Select...',
      clearable: true,
      allowClearingDisabled: false,
      clearAllText: 'Clear all',
      clearValueText: 'Clear value',
      alwaysOpen: false,
      openOnFocus: false,
      autoFocus: false,
      tabIndex: 0,
      backspaceRemoves: true,
      deleteRemoves: true,
      limit: Infinity,
      limitText: vi.fn(),
      valueFormat: 'id',
      delimiter: ',',
      openMenu: vi.fn(),
      closeMenu: vi.fn(),
      clear: vi.fn(),
      focusInput: vi.fn(),
      blurInput: vi.fn(),
      getSelectedNodes: vi.fn(() => []),
      getNode: vi.fn(() => null),
      isSelected: vi.fn(() => false),
      toggleExpanded: vi.fn(),
      select: vi.fn(),
      loadChildrenOptions: vi.fn(),
      getInstanceId: vi.fn(() => 'test'),
      getValue: vi.fn(),
      initialize: vi.fn(),
      buildForestState: vi.fn(),
      shouldOptionBeIncludedInSearchResult: vi.fn(() => false),
      traverseAllNodesByIndex: vi.fn(),
      extractCheckedNodeIdsFromValue: vi.fn(() => []),
      fixSelectedNodeIds: vi.fn(),
      enhancedNormalizer: vi.fn((o) => o),
      toggleMenu: vi.fn(),
      resetHighlightedOptionWhenNecessary: vi.fn(),
      highlightFirstOption: vi.fn(),
      highlightPrevOption: vi.fn(),
      highlightNextOption: vi.fn(),
      highlightLastOption: vi.fn(),
      visibleOptionIds: [],
      setMenuGetter: vi.fn(),
      setControlGetter: vi.fn(),
      setInputGetter: vi.fn(),
      handleLocalSearch: vi.fn(),
      handleRemoteSearch: vi.fn(),
      resetSearchQuery: vi.fn(),
      loadRootOptions: vi.fn(),
      callLoadOptionsProp: vi.fn(),
      handleMouseDown: vi.fn(),
      setup: vi.fn(),
      onMount: vi.fn(),
      onUnmount: vi.fn(),
      remoteSearch: {},
      noOptionsText: 'No options available.',
      noResultsText: 'No results found.',
      searchPromptText: 'Type to search...',
      getRemoteSearchEntry: vi.fn(() => ({ isLoaded: false, isLoading: false, loadingError: '', options: [] })),
      openDirection: 'auto',
      getMenu: vi.fn(() => null),
      getControl: vi.fn(() => null),
      menu: {
        isOpen: false,
        current: null,
        lastScrollPosition: 0,
        placement: 'bottom',
      },
      getValueContainer: vi.fn(() => null),
      setValueContainerGetter: vi.fn(),
      setupHandleClickOutside: vi.fn(),
    }

    const wrapper = mount(SingleValue, {
      global: {
        provide: {
          [TRESELECT_INSTANCE_KEY as symbol]: computed(() => mockInstance),
        },
      },
    })

    expect(wrapper.find('.vue-treeselect__single-value').exists()).toBe(false)
  })

  it('should not render when searchQuery is not empty', () => {
    const mockNode: TreeselectNode = {
      id: 'a',
      label: 'Option A',
      lowerLabel: 'option a',
      lowerCased: {},
      nestedSearchLabel: 'option a',
      isLeaf: true,
      isBranch: false,
      isDisabled: false,
      isNew: false,
      isMatched: false,
      isHighlighted: false,
      hasMatchedDescendants: false,
      hasDisabledDescendants: false,
      hasChildren: false,
      hasLoadedChildren: true,
      isExpanded: false,
      isExpandedOnSearch: false,
      showAllChildrenOnSearch: false,
      isLoading: false,
      loadingError: '',
      childrenStates: { isLoaded: true, isLoading: false, loadingError: '' },
      count: { ALL_CHILDREN: 0, ALL_DESCENDANTS: 0, LEAF_CHILDREN: 0, LEAF_DESCENDANTS: 0 },
      isSelected: true,
      level: 0,
      index: [0],
      ancestors: [],
      parentNode: null,
      isRootNode: true,
      isFallbackNode: false,
      children: [],
      raw: { id: 'a', label: 'Option A' },
    }

    const mockInstance: TreeselectInstance = {
      trigger: {
        isFocused: false,
        searchQuery: 'search',
      },
      menuIsOpen: false,
      currentHighlightedOptionId: null,
      selectedNodes: [mockNode],
      hasValue: true,
      single: true,
      multiple: false,
      hasBranchNodes: false,
      localSearch: {
        active: false,
        noResults: true,
        countMap: {},
      },
      forest: {
        normalizedOptions: [],
        nodeMap: {},
        checkedStateMap: {},
        selectedNodeIds: [],
        selectedNodeMap: {},
      },
      rootOptionsStates: {
        isLoaded: false,
        isLoading: false,
        loadingError: '',
      },
      showCount: false,
      showCountOf: 'ALL_CHILDREN',
      showCountOnSearchComputed: false,
      noChildrenText: 'No sub-options.',
      loadingText: 'Loading...',
      retryTitle: 'Click to retry',
      retryText: 'Retry?',
      shouldFlattenOptions: false,
      shouldExpand: vi.fn(),
      shouldShowOptionInMenu: vi.fn(() => true),
      setCurrentHighlightedOption: vi.fn(),
      removeLastValue: vi.fn(),
      disabled: false,
      searchable: true,
      placeholder: 'Select...',
      clearable: true,
      allowClearingDisabled: false,
      clearAllText: 'Clear all',
      clearValueText: 'Clear value',
      alwaysOpen: false,
      openOnFocus: false,
      autoFocus: false,
      tabIndex: 0,
      backspaceRemoves: true,
      deleteRemoves: true,
      limit: Infinity,
      limitText: vi.fn(),
      valueFormat: 'id',
      delimiter: ',',
      openMenu: vi.fn(),
      closeMenu: vi.fn(),
      clear: vi.fn(),
      focusInput: vi.fn(),
      blurInput: vi.fn(),
      getSelectedNodes: vi.fn(() => [mockNode]),
      getNode: vi.fn(() => mockNode),
      isSelected: vi.fn(() => true),
      toggleExpanded: vi.fn(),
      select: vi.fn(),
      loadChildrenOptions: vi.fn(),
      getInstanceId: vi.fn(() => 'test'),
      getValue: vi.fn(),
      initialize: vi.fn(),
      buildForestState: vi.fn(),
      shouldOptionBeIncludedInSearchResult: vi.fn(() => false),
      traverseAllNodesByIndex: vi.fn(),
      extractCheckedNodeIdsFromValue: vi.fn(() => []),
      fixSelectedNodeIds: vi.fn(),
      enhancedNormalizer: vi.fn((o) => o),
      toggleMenu: vi.fn(),
      resetHighlightedOptionWhenNecessary: vi.fn(),
      highlightFirstOption: vi.fn(),
      highlightPrevOption: vi.fn(),
      highlightNextOption: vi.fn(),
      highlightLastOption: vi.fn(),
      visibleOptionIds: [],
      setMenuGetter: vi.fn(),
      setControlGetter: vi.fn(),
      setInputGetter: vi.fn(),
      handleLocalSearch: vi.fn(),
      handleRemoteSearch: vi.fn(),
      resetSearchQuery: vi.fn(),
      loadRootOptions: vi.fn(),
      callLoadOptionsProp: vi.fn(),
      handleMouseDown: vi.fn(),
      setup: vi.fn(),
      onMount: vi.fn(),
      onUnmount: vi.fn(),
      remoteSearch: {},
      noOptionsText: 'No options available.',
      noResultsText: 'No results found.',
      searchPromptText: 'Type to search...',
      getRemoteSearchEntry: vi.fn(() => ({ isLoaded: false, isLoading: false, loadingError: '', options: [] })),
      openDirection: 'auto',
      getMenu: vi.fn(() => null),
      getControl: vi.fn(() => null),
      menu: {
        isOpen: false,
        current: null,
        lastScrollPosition: 0,
        placement: 'bottom',
      },
      getValueContainer: vi.fn(() => null),
      setValueContainerGetter: vi.fn(),
      setupHandleClickOutside: vi.fn(),
    }

    const wrapper = mount(SingleValue, {
      global: {
        provide: {
          [TRESELECT_INSTANCE_KEY as symbol]: computed(() => mockInstance),
        },
      },
    })

    expect(wrapper.find('.vue-treeselect__single-value').exists()).toBe(false)
  })
})
